unzip("C:/Andrea/IBG_SupportingInfo/Classes/DataScience_Specialization/ExploratoryDataAnalysis/CourseProjects/exdata-data-household_power_consumption.zip")
fullRecord <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", quote = "")
fullRecord$Date2 <- as.Date( as.character(fullRecord$Date), "%d/%m/%Y")
SubSet <- subset(fullRecord, Date2 >= as.Date("2007-02-01") & Date2 < as.Date("2007-02-03"))
SubSet$DateTime <- as.POSIXct(paste(SubSet$Date2, SubSet$Time), format="%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfcol = c(2, 2))
plot(SubSet$DateTime, as.numeric(as.character(SubSet$Global_active_power)), type="n", ylab = "Global Active Power", xlab = "")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Global_active_power)), type="l")
plot(SubSet$DateTime, as.numeric(as.character(SubSet$Sub_metering_1)), type="n", ylab = "Energy sub metering", xlab = "")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Sub_metering_1)), type="l", col="black")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Sub_metering_2)), type="l", col="red")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Sub_metering_3)), type="l", col="blue")
legend("topright",legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"),lty=c(1,1,1), bty="n", cex=.8)
plot(SubSet$DateTime, as.numeric(as.character(SubSet$Voltage)), type="n", ylab = "Voltage", xlab = "datetime")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Voltage)), type="l")
plot(SubSet$DateTime, as.numeric(as.character(SubSet$Global_reactive_power)), type="n", ylab = "Global_reactive_power", xlab = "datetime")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Global_reactive_power)), type="l")
dev.off()