unzip("C:/Andrea/IBG_SupportingInfo/Classes/DataScience_Specialization/ExploratoryDataAnalysis/CourseProjects/exdata-data-household_power_consumption.zip")
fullRecord <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", quote = "")
fullRecord$Date2 <- as.Date( as.character(fullRecord$Date), "%d/%m/%Y")
SubSet <- subset(fullRecord, Date2 >= as.Date("2007-02-01") & Date2 < as.Date("2007-02-03"))
SubSet$DateTime <- as.POSIXct(paste(SubSet$Date2, SubSet$Time), format="%Y-%m-%d %H:%M:%S")
png("plot2.png")
plot(SubSet$DateTime, as.numeric(as.character(SubSet$Global_active_power)), type="n", ylab = "Global Active Power (killwatts)", xlab = "")
lines(SubSet$DateTime, as.numeric(as.character(SubSet$Global_active_power)), type="l")
dev.off()